---
name: New Contributor Onboarding
description: Submit this issue to start your journey as a contributor
title: "[NEW CONTRIBUTOR] "
labels: ["new-contributor"]
---

## Welcome to BuilderHub! 🎉

Thank you for your interest in contributing to this open-source project. To get started:

1. Submitting this issue will trigger an invitation to become a collaborator.
2. Once you accept the invitation, you can submit pull requests.
3. Your first contribution will be adding your username to **docs/CONTRIBUTORS.md**.

## Please provide the following information

- **Your Name:**  
  `e.g., John Doe`
- **Your GitHub Username:**  
  `e.g., @johndoe`
- **Why do you want to contribute?** (Optional)  
  `e.g., I want to improve documentation and learn more about BuilderHub.`

---

After submitting this issue, check your email for the collaborator invitation. Once accepted, proceed to make your first PR by adding your username to **docs/CONTRIBUTORS.md**.
